# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dr. G
tagline:          'Not the useful kind'
description:      'Not the useful kind... Currently a PostDoc @ Caltech/JPL.'
url:              http://www.castiglionis.com
baseurl:          /

author:
  name:           'Giacomo Castiglioni'
  url:            http://www.castiglionis.com

paginate:         1

excerpt_separator: <!--more-->

# Custom vars
version:          1.0.2

  # # scholar
  # scholar:
  #   bibliography: CV.bib

github:
  repo:           https://github.com/castigli/castigli.github.io

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll/scholar
  - redcarpet
  # - pygments.rb

exclude:
  - hyde-giacomo.sublime-project
  - hyde-giacomo.sublime-workspace
